// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dashboard/v1/dashboard.proto

package dashboard

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListPullRequestsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPullRequestsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPullRequestsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPullRequestsRequestMultiError, or nil if none found.
func (m *ListPullRequestsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPullRequestsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListPullRequestsRequestMultiError(errors)
	}
	return nil
}

// ListPullRequestsRequestMultiError is an error wrapping multiple validation
// errors returned by ListPullRequestsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListPullRequestsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPullRequestsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPullRequestsRequestMultiError) AllErrors() []error { return m }

// ListPullRequestsRequestValidationError is the validation error returned by
// ListPullRequestsRequest.Validate if the designated constraints aren't met.
type ListPullRequestsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPullRequestsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPullRequestsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPullRequestsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPullRequestsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPullRequestsRequestValidationError) ErrorName() string {
	return "ListPullRequestsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPullRequestsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPullRequestsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPullRequestsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPullRequestsRequestValidationError{}

// Validate checks the field values on StreamPullRequestsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StreamPullRequestsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StreamPullRequestsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StreamPullRequestsRequestMultiError, or nil if none found.
func (m *StreamPullRequestsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StreamPullRequestsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return StreamPullRequestsRequestMultiError(errors)
	}
	return nil
}

// StreamPullRequestsRequestMultiError is an error wrapping multiple validation
// errors returned by StreamPullRequestsRequest.ValidateAll() if the
// designated constraints aren't met.
type StreamPullRequestsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StreamPullRequestsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StreamPullRequestsRequestMultiError) AllErrors() []error { return m }

// StreamPullRequestsRequestValidationError is the validation error returned by
// StreamPullRequestsRequest.Validate if the designated constraints aren't met.
type StreamPullRequestsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamPullRequestsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamPullRequestsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamPullRequestsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamPullRequestsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamPullRequestsRequestValidationError) ErrorName() string {
	return "StreamPullRequestsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StreamPullRequestsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamPullRequestsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamPullRequestsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamPullRequestsRequestValidationError{}

// Validate checks the field values on ListPullRequestsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPullRequestsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPullRequestsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPullRequestsResponseMultiError, or nil if none found.
func (m *ListPullRequestsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPullRequestsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPullRequestsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPullRequestsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPullRequestsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListPullRequestsResponseMultiError(errors)
	}
	return nil
}

// ListPullRequestsResponseMultiError is an error wrapping multiple validation
// errors returned by ListPullRequestsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListPullRequestsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPullRequestsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPullRequestsResponseMultiError) AllErrors() []error { return m }

// ListPullRequestsResponseValidationError is the validation error returned by
// ListPullRequestsResponse.Validate if the designated constraints aren't met.
type ListPullRequestsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPullRequestsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPullRequestsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPullRequestsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPullRequestsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPullRequestsResponseValidationError) ErrorName() string {
	return "ListPullRequestsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPullRequestsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPullRequestsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPullRequestsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPullRequestsResponseValidationError{}

// Validate checks the field values on Repository with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Repository) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Repository with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RepositoryMultiError, or
// nil if none found.
func (m *Repository) ValidateAll() error {
	return m.validate(true)
}

func (m *Repository) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	for idx, item := range m.GetPullrequests() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RepositoryValidationError{
						field:  fmt.Sprintf("Pullrequests[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RepositoryValidationError{
						field:  fmt.Sprintf("Pullrequests[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RepositoryValidationError{
					field:  fmt.Sprintf("Pullrequests[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return RepositoryMultiError(errors)
	}
	return nil
}

// RepositoryMultiError is an error wrapping multiple validation errors
// returned by Repository.ValidateAll() if the designated constraints aren't met.
type RepositoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RepositoryMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RepositoryMultiError) AllErrors() []error { return m }

// RepositoryValidationError is the validation error returned by
// Repository.Validate if the designated constraints aren't met.
type RepositoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RepositoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RepositoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RepositoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RepositoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RepositoryValidationError) ErrorName() string { return "RepositoryValidationError" }

// Error satisfies the builtin error interface
func (e RepositoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRepository.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RepositoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RepositoryValidationError{}

// Validate checks the field values on PullRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PullRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PullRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PullRequestMultiError, or
// nil if none found.
func (m *PullRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PullRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Url

	// no validation rules for User

	// no validation rules for SourceBranch

	// no validation rules for TargetBranch

	// no validation rules for LastUpdatedAt

	// no validation rules for Status

	if len(errors) > 0 {
		return PullRequestMultiError(errors)
	}
	return nil
}

// PullRequestMultiError is an error wrapping multiple validation errors
// returned by PullRequest.ValidateAll() if the designated constraints aren't met.
type PullRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PullRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PullRequestMultiError) AllErrors() []error { return m }

// PullRequestValidationError is the validation error returned by
// PullRequest.Validate if the designated constraints aren't met.
type PullRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PullRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PullRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PullRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PullRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PullRequestValidationError) ErrorName() string { return "PullRequestValidationError" }

// Error satisfies the builtin error interface
func (e PullRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPullRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PullRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PullRequestValidationError{}
